handle: dummy
isFrontendEnabled: '1'
name: Dummy
orderCondition:
  class: craft\commerce\elements\conditions\orders\GatewayOrderCondition
  elementType: craft\commerce\elements\Order
  fieldContext: global
paymentType: purchase
sortOrder: 99
type: craft\commerce\gateways\Dummy
