defaultPlacement: end
descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: tShirts
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
isStructure: false
maxLevels: null
maxVariants: 3
name: T-Shirts
productFieldLayouts:
  4a9cfc08-a77a-4ebe-af7f-9463294912e1:
    cardThumbAlignment: end
    cardView:
      - defaultSku
      - defaultPrice
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-30T08:57:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 9c3c9d19-4c34-43c2-aea7-1dd4cc2e2978
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2025-09-30T08:57:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 15eed0b0-5559-4ea6-8ad3-e5133ac93d11
            userCondition: null
            warning: null
          -
            dateAdded: '2025-09-30T09:14:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c0eec0f7-5f7a-43c5-847f-4a4eeefb5692 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64a39c61-8242-48a4-8dfa-79160c63cabf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-30T12:39:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5690c58d-c74b-41fb-b055-e88a40e6c329 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5a4c91b-908e-4541-b8e1-11b1aef5a2ca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62d42c58-cb4b-466b-8a1d-264fbc4db7f7
        userCondition: null
productTitleFormat: ''
productTitleTranslationKeyFormat: null
productTitleTranslationMethod: site
propagationMethod: all
siteSettings:
  965b800e-6cb0-4618-b771-c8431ea77f46: # craft
    enabledByDefault: true
    hasUrls: true
    template: products/_entry
    uriFormat: 't-shirts/{slug}'
skuFormat: ''
variantFieldLayouts:
  76b062a1-ecc5-41a5-b996-440271defa51:
    cardThumbAlignment: end
    cardView:
      - sku
      - priceView
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-30T08:57:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 03ce0d9b-f1f6-46b2-b796-4c7e880e2f54
            userCondition: null
            warning: null
            width: 100
          -
            attribute: sku
            dateAdded: '2025-09-30T08:57:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: bbe276d4-b436-4b76-aca2-f782f0e47add
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2025-09-30T08:57:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 10444151-1604-46f6-96a4-42002b455f8f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2025-09-30T08:57:17+00:00'
            defaultAllowOutOfStockPurchases: false
            defaultInventoryTracked: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: 90f5a7a8-5532-47f7-9d7a-c5a0a63eb397
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2025-09-30T08:57:17+00:00'
            defaultAvailableForPurchase: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: e888ee2b-6e92-49ac-94ff-68fdc8c4652a
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2025-09-30T08:57:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: 6890626a-2019-4d8d-9bc1-1e6f604a5fbc
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2025-09-30T08:57:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: 6628c6a9-a656-4838-bd1a-4d914ce81127
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2025-09-30T08:57:17+00:00'
            defaultPromotable: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: f3a3525a-5bc0-4101-9951-c9ba1f223a50
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2025-09-30T08:57:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 077a849b-ab2d-4b28-b7b5-483d7dadcb78
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2025-09-30T08:57:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: 95376e7b-b442-4861-9ecb-df9e7a8ca8cf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 67a8d1db-09e4-49ee-aef1-ca03ce89e721
        userCondition: null
variantTitleFormat: '{product.title}'
variantTitleTranslationKeyFormat: null
variantTitleTranslationMethod: site
