altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a6f3907b-0798-4cd9-8c55-780b859d211c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-30T12:41:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a4ca7975-1ebb-4447-8176-d956d8f06c97
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ca663469-2145-4db5-a4aa-6108132b5154
        userCondition: null
fs: localUploads
handle: productImages
name: 'Product Images'
sortOrder: 1
subpath: product-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
